
service: aws-nodejs # NOTE: update this with your service name
app: foobar
tenant: stevewestergaard

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  foo:
    handler: foo.foo
    events:
      - http:
          path: foo
          method: get
          cors: true

plugins: 
  - serverless-offline
  - serverless-apm-plugin